# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AbstractNoncontextualMAB": "00_abstractions.ipynb",
         "AbstractContextualMAB": "00_abstractions.ipynb",
         "AbstractSolver": "00_abstractions.ipynb",
         "AbstractContextualSolver": "00_abstractions.ipynb",
         "sigmoid": "01_multi_armed_bandits.ipynb",
         "non_contextual_categorical_bandit": "01_multi_armed_bandits.ipynb",
         "contextual_categorical_bandit": "01_multi_armed_bandits.ipynb",
         "contextual_categorical_get_optimal_arm": "01_multi_armed_bandits.ipynb",
         "NonlinearContextualCategoricalBandit": "01_multi_armed_bandits.ipynb",
         "contextual_numerical_bandit": "01_multi_armed_bandits.ipynb",
         "contextual_numerical_get_optimal_arm": "01_multi_armed_bandits.ipynb",
         "NonlinearContextualNumericalBandit": "01_multi_armed_bandits.ipynb",
         "OnlineLogisticRegression": "02_models.ipynb",
         "BayesLinReg": "02_models.ipynb",
         "BatchBayesLinReg": "02_models.ipynb",
         "SimpleModel": "02_models.ipynb",
         "VanillaEnsemble": "03_ensembles.ipynb",
         "OnlineBootstrapEnsemble": "03_ensembles.ipynb",
         "AB": "04_solvers.ipynb",
         "BetaBandit": "04_solvers.ipynb",
         "LogisticThompsonSampler": "04_solvers.ipynb",
         "GaussianBandit": "04_solvers.ipynb",
         "GaussianContextualSampler": "04_solvers.ipynb",
         "GaussianCategoricalBandit": "04_solvers.ipynb",
         "plot_regret": "99_helpers.ipynb",
         "showcase_code": "99_helpers.ipynb",
         "iters": "99_helpers.ipynb",
         "l2": "99_helpers.ipynb",
         "n_std": "99_helpers.ipynb",
         "plot_online_logreg": "99_helpers.ipynb",
         "prettify_ax": "99_helpers.ipynb",
         "sample": "99_helpers.ipynb",
         "plot_param_through_time": "99_helpers.ipynb"}

modules = ["abstractions.py",
           "multi_armed_bandits.py",
           "models.py",
           "ensembles.py",
           "solvers.py",
           "helpers.py"]

doc_url = "https://Thomas Rost.github.io/thompson_sampling/"

git_url = "https://github.com/Thomas Rost/thompson_sampling/tree/master/"

def custom_doc_links(name): return None
