# AUTOGENERATED! DO NOT EDIT! File to edit: 01_multi_armed_bandits.ipynb (unless otherwise specified).

__all__ = ['non_contextual_categorical_customer_reaction', 'contextual_numerical_customer_reaction']

# Cell
import numpy as np
import scipy.stats as stats



# Cell
def non_contextual_categorical_customer_reaction(choice:int, theta:np.array)->bool:

    # draw a number between 0 and 1, if it's smaller than the theta, return reward
    if np.random.random() < theta[choice]:
        reaction = True
    else:
        reaction = False

    return reaction

# Cell
def contextual_numerical_customer_reaction(context:np.array, choice:int, theta:np.array, noise=float)->float:
    features  = np.append(context,choice)

    # decide on which slope to use depending on whether a dog is present or not
    m = theta[0] if features[1] else theta[1]
    intercept = 0 if features[1] else 0

    # $y = x \cdot m + t + \epsilon $
    y = features[0] * m + intercept +  np.random.normal(0,noise)


    return y