# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AbstractSolver": "00_abstractions.ipynb",
         "AbstractContextualSolver": "00_abstractions.ipynb",
         "non_contextual_categorical_customer_reaction": "01_multi_armed_bandits.ipynb",
         "contextual_numerical_customer_reaction": "01_multi_armed_bandits.ipynb",
         "SimpleModel": "02_models.ipynb",
         "VanillaEnsemble": "03_ensembles.ipynb",
         "OnlineBootstrapEnsemble": "03_ensembles.ipynb",
         "AB": "04_solvers.ipynb",
         "BetaBandit": "04_solvers.ipynb"}

modules = ["abstractions.py",
           "multi_armed_bandits.py",
           "models.py",
           "ensembles.py",
           "solvers.py"]

doc_url = "https://Thomas Rost.github.io/thompson_sampling_edu/"

git_url = "https://github.com/Thomas Rost/thompson_sampling_edu/tree/master/"

def custom_doc_links(name): return None
